language: node_js
node_js:
- node
deploy:
- skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: npm run deploy-branch
  on:
    all_branches: true
    condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
env:
  global:
    secure: y5Ugx0dFkw+Ad1Ar3Umh8Ym6xbrQwoX2XDr8XTa7Cqi7R6Rg0c65RvKqs8Lj0E51yEt1OUNSO10cigU5YXB/i4fQ8iYemM5Z4vO6SfIcV05LrfdzSljbFeN/OdoX38a40I7ws7tIyZ+3EEBAnwdwcAXY0+1czWtCr85koxSjpOiAQc52+bkEdmvya1F1HJ0bQoAIznNeRn+rkgagcHjPvHY+0Qp2NBwj+nH3ImJr7Fcjg3pKWgPSoMQ9igseRLs86mpQOWhdNIMdCXLB3/nxWtEaN6wMLLbctuG4z9jfSG+8DDp53d7RLFxTFJnn9r53EWPSyb4/6bCkp0Bql8jRl/sU58TssmRTAiJif8soAuUM0q7I5CbrEAon4VsvixDWbKSQES4ggOsRv+fWbmB0pXli7wlXKy8IMS92MOG03DxiMcRTAI4v85uqResFz0tz9NspwvbWw3tyTgFQW1nYASAPiYRIaKSHpeyQBG0c8e+RYiFl3q2sBIWlLdVBVA/v1aqyXks2ZGmkLqbZPyUltVJZJe5TcUsdDlyvCM9gNnBV3wM+dvHtvvzOXBBu8zZtESa0s7fX6AipgiNbrRzoeQ9bieQ9buRPGUSuN2FmXbBSiipo87ihDCUVTN2g1cf6zX9lP+O+63Z2WCRy62QjvMrQz2zyb8/gv+CFW+s8/5o=
